"""warrior refactor

Revision ID: 53cdf0f444c8
Revises: 
Create Date: 2026-03-01 18:17:56.689176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53cdf0f444c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('item_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('warrior_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('vip_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warrior_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_hp', sa.Integer(), nullable=False),
    sa.Column('base_attack', sa.Integer(), nullable=False),
    sa.Column('base_defense', sa.Integer(), nullable=False),
    sa.Column('base_speed', sa.Integer(), nullable=False),
    sa.Column('hp_growth', sa.Integer(), nullable=False),
    sa.Column('attack_growth', sa.Integer(), nullable=False),
    sa.Column('defense_growth', sa.Integer(), nullable=False),
    sa.Column('speed_growth', sa.Integer(), nullable=False),
    sa.Column('skill1_id', sa.Integer(), nullable=True),
    sa.Column('skill1_unlock_level', sa.Integer(), nullable=True),
    sa.Column('skill2_id', sa.Integer(), nullable=True),
    sa.Column('skill2_unlock_level', sa.Integer(), nullable=True),
    sa.Column('skill3_id', sa.Integer(), nullable=True),
    sa.Column('skill3_unlock_level', sa.Integer(), nullable=True),
    sa.Column('sprite_base', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('exp', sa.Integer(), nullable=True),
    sa.Column('battles_wins', sa.Integer(), nullable=True),
    sa.Column('battles_loses', sa.Integer(), nullable=True),
    sa.Column('bank_zeny', sa.Integer(), nullable=True),
    sa.Column('sprite_overworld', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('player_warriors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('exp', sa.Integer(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('bonus_attack', sa.Integer(), nullable=True),
    sa.Column('bonus_defense', sa.Integer(), nullable=True),
    sa.Column('bonus_hp', sa.Integer(), nullable=True),
    sa.Column('bonus_speed', sa.Integer(), nullable=True),
    sa.Column('unused_stat_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['warrior_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_warriors')
    op.drop_table('players')
    op.drop_table('warrior_templates')
    op.drop_table('vip')
    op.drop_table('team')
    op.drop_table('inventory')
    op.drop_table('accounts')
    # ### end Alembic commands ###
